name: CI

on:
  push:
    branches: [master]
  merge_group: {}
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

env:
  RUSTFLAGS: "-Dwarnings"
  MSRV: 1.63.0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            platform: ubuntu-latest
            rust: stable

          - target: x86_64-unknown-linux-gnu
            platform: ubuntu-latest
            rust: nightly

          - target: x86_64-apple-darwin
            platform: macos-latest
            rust: stable

          - target: x86_64-pc-windows-msvc
            platform: windows-latest
            rust: stable
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy --release
      - name: Run Tests
        uses: taiki-e/install-action@nextest
      - run: cargo nextest run --target ${{ matrix.target }} --release
